version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/mysql:8.3

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Run your tests
      - run:
          name: TestCalculadora
          command: mvn -Dtest=Calculadora* test

      - run:
          name: UnitTestUserService
          command: mvn -Dtest=UserServiceUnitTest -Dsurefire.printSummary=true test

      - run:
          name: FunctionalTestCRUDService
          command: mvn -Dtest=CRUDSeleniumTest -Dsurefire.printSummary=true test

  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main