version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      
      # Instalar dependencias necesarias
      - run:
          name: Instalar Chrome y sus dependencias
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      # Instalar WebDriver para Chrome (chromedriver)
      - run:
          name: Instalar ChromeDriver
          command: |
            sudo apt-get install -y unzip
            wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

      # Construir el proyecto
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Ejecutar pruebas con Selenium
      - run:
          name: Selenium Tests
          command: mvn -Dtest=CRUDSeleniumTest -Dsurefire.printSummary=true test

  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main