version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Start Docker Compose
          command: docker-compose -f docker-compose.yml up -d

      # Ejecutar las pruebas
      - run:
          name: Run Integration Tests
          command: mvn -Dtest=UserServiceTest test

      - run:
          name: Stop Docker Compose
          command: docker-compose down

  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main