version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout  # Checkout del código fuente
      
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Ejecutar pruebas con Selenium
      - run:
          name: Unit Tests
          command: mvn -Dtest=UserServiceUnitTest -Dsurefire.printSummary=true test

  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main