version: 2.1

jobs:

  build:

    docker:
      - image: cimg/openjdk:17.0

    steps:
      # Checkout the code as the first step.
      - checkout

      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: TestCalculadora
          command: mvn -Dtest=Calculadora* test

      - run:
          name: UnitTestUserSevice
          command: mvn -Dtest=UserServiceUnitTest -Dsurefire.printSummary=true test
    
  test:
    docker:
        - image: cimg/openjdk:17.0

      steps:
        - checkout

        - run:
            name: TestCalculadora
            command: mvn -Dtest=Calculadora* test

        - run:
            name: UnitTestUserSevice 
            command: mvn -Dtest=UserServiceUnitTest -Dsurefire.printSummary=true test
  
  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
        filters:
          branches:
            only:
              - main
