version: '2.1'

services:
  app:
    build:
      context: .
    image: tu-imagen-java
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=calidadSoftware2024
      - DB_USER=root
      - DB_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: calidadSoftware2024
    ports:
      - "3307:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge