version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout  # Checkout del código fuente
      
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            sudo apt-get install -y curl
            sudo apt-get install -y unzip
            sudo apt-get install -y libx11-xcb1 libgbm-dev libxrandr2 libxss1 libasound2 libnss3
      - run:
          name: Install Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - run:
          name: Install ChromeDriver
          command: |
            CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\([0-9]*\)\.[0-9]*\.[0-9]*/\1/')
            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
      # Construir el proyecto
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Ejecutar pruebas con Selenium
      - run:
          name: Selenium Tests
          command: mvn -Dtest=CRUDSeleniumTest -Dsurefire.printSummary=true test

  deployment:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run: echo "Deploying... deploy done"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main